### ISSUE TITLE
不能编译到lean openwrt里面

### ISSUE THREAD

**Issue by tcsr200722** [lisaac/luci-lib-docker#1]

**Comment by lisaac** [comment]
请给出具体信息或log

**Comment by lisaac** [comment]
luci-app-docker项目名与lean仓库有些文件冲突。
已经改为luci-app-dockerman，已经测试能够正常编译通过。

**Comment by tcsr200722** [comment]
谢谢！确实可以编译进去了！再次表示感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lisaac"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月9日(星期一) 中午1:15
收件人:&nbsp;"lisaac/luci-lib-docker"<luci-lib-docker@noreply.github.com&gt;;
抄送:&nbsp;"350524166"<350524166@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lisaac/luci-lib-docker] 不能编译到lean openwrt里面 (#1)




Closed #1.

**Comment by tcsr200722** [comment]
大佬，能否加一个更新按钮？镜像源码更新了，不用重新设置一次！


 
---原始邮件---
发件人: "lisaac"<notifications@github.com&gt;
发送时间: 2019年12月9日 13:15:47
收件人: "lisaac/luci-lib-docker"<luci-lib-docker@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"tcsr200722"<350524166@qq.com&gt;;
主题: Re: [lisaac/luci-lib-docker] 不能编译到lean openwrt里面 (#1)



luci-app-docker项目名与lean仓库有些文件冲突。
 已经改为luci-app-dockerman，已经测试能够正常编译通过。

**Comment by lisaac** [comment]
可以，后续加上
