### ISSUE TITLE
哪里下载docker-ce，官方openwrt

### ISSUE THREAD

**Issue by aogg** [lisaac/luci-lib-docker#3]
docker官方文档没有opkg安装命令的啊

**Comment by lisaac** [comment]
最新官方已经将docker-ce包名改为docker，依赖问题可以暂时使用强制安装的方法，近期会更新

**Comment by haze1986** [comment]
没有docker-ce，安装了dockerman和docker和luci-lib-docker，docker页面还是只有"configuration"

**Comment by lisaac** [comment]
> 没有docker-ce，安装了dockerman和docker和luci-lib-docker，docker页面还是只有"configuration"

dockerman 只是 ui，请安装 docker
